### ISSUE TITLE
Bug: Fails in Ruby 3.0.1

### ISSUE THREAD

**Issue by jikkujose** [Martin-Nyaga/termplot#2]
First of all, brilliant work! I am so impressed by the gem. The screenshots looks amazing!!!! I really want to give this a try, but met with some road blocks. 

Platform: Mac 11.2.3

Gem fails for most examples with the following trace when tested in `3.0.1` (it worked in `2.7.1`):

```
/Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/widgets/base_widget.rb:22:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/consumers/single_source_consumer.rb:28:in `new'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/consumers/single_source_consumer.rb:28:in `widget'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/consumers/single_source_consumer.rb:10:in `positioned_widgets'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/consumers/base_consumer.rb:17:in `initialize'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/cli.rb:22:in `new'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/cli.rb:22:in `run_consumer'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/lib/termplot/cli.rb:10:in `run'
        from /Users/username/.gem/ruby/3.0.1/gems/termplot-0.3.0/bin/termplot:5:in `<top (required)>'
        from /Users/username/.gem/ruby/3.0.1/bin/termplot:23:in `load'
        from /Users/username/.gem/ruby/3.0.1/bin/termplot:23:in `<main>'
```

**Comment by Martin-Nyaga** [comment]
Hi @jikkujose, thanks for giving this a go and for your feedback!

I haven't tried running this on ruby 3+ yet. I'll take a look at this when I have some time.

**Comment by Martin-Nyaga** [comment]
Hi @jikkujose, I had some time this evening. I was able to replicate this and I've now fixed it and released version 0.3.1. I tested all the examples and they now work correctly on ruby 3.0.0 (you had 3.0.1, but it shouldn't make a difference). You can install the newer version and let me know if everything works fine.

**Comment by jikkujose** [comment]
Now it works great! But sadly some examples don't work in Mac. If you don't mind, I can attempt a PR with some platform agnostic examples. Something ideas I have in my mind for good examples are:

- Short
- Platform agnostic
- Very less or zero dependence on an external tool
- Readily editable

For instance:

`termplot --command 'ruby -e "puts rand(10)/10.0"'`

**Comment by Martin-Nyaga** [comment]
Oh, that sounds great! I agree that the examples right now are not the best; they are a little convoluted and only tested on linux. I'm very happy to take a look at some recommendations in a PR.

In the meantime, I will close this issue as the specific ruby-3 bugs are fixed.
